backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "writing" # Used in routes, e.g., /admin/collections/writing
    label: "Writing" # Used in the UI
    folder: "_posts/writing" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "writing",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
